#!/bin/bash
#
# Installs Docker Compose.
# Source: https://docs.docker.com/compose/install/
#
set -o nounset -o errexit -o pipefail

VERSION=1.24.0  # From https://github.com/docker/compose/releases

sudo curl -L "https://github.com/docker/compose/releases/download/$VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
