---
- name: Add Google Chrome repository
  become: yes
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: chrome.list

- name: Add Google Chrome apt signing key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install Google Chrome
  become: yes
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
