---
- name: Check if zoom is installed
  command: dpkg-query -W zoom
  register: zoom_check_deb
  failed_when: zoom_check_deb.rc > 1
  changed_when: zoom_check_deb.rc == 1

- name: Install zoom
  apt: deb="https://zoom.us/client/latest/zoom_amd64.deb"
  become: yes
  when: zoom_check_deb.rc == 1
