# tig
# https://github.com/jonas/tig
# Binary will be installed in ~/opt/bin/tig
# Configuration in ~/opt/etc/tigrc
---
- stat: path="{{ home_dir }}/opt/bin/tig"
  register: tig_file

- name: Download tig tarball
  get_url:
    url: https://github.com/jonas/tig/releases/download/tig-2.4.1/tig-2.4.1.tar.gz
    dest: /tmp/tig.tar.gz
    checksum: sha256:b6b6aa183e571224d0e1fab3ec482542c1a97fa7a85b26352dc31dbafe8558b8
    timeout: 300
  when: tig_file.stat.exists == False

- name: Create /tmp/tig
  file: path=/tmp/tig state=directory
  when: tig_file.stat.exists == False

- name: Extract tig tarball
  unarchive:
    src: /tmp/tig.tar.gz
    dest: /tmp/tig
    extra_opts: [--strip-components=1]
  when: tig_file.stat.exists == False

- name: Install tig
  shell: |
    make configure && \
    ./configure && \
    make prefix={{ home_dir }}/opt && \
    make install prefix={{ home_dir }}/opt
  args:
    chdir: /tmp/tig
  when: tig_file.stat.exists == False
