---
# https://keybase.io/docs/the_app/install_linux
- name: Install Keybase
  shell: |
    cd /tmp && \
    curl -O https://prerelease.keybase.io/keybase_amd64.deb && \
    sudo dpkg -i keybase_amd64.deb && \
    sudo apt-get install -f && \
    run_keybase
  args:
    creates: /usr/bin/keybase
