---
- name: Add git PPA
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
    codename: '{{ distrib_codename }}'

- name: Install git
  become: yes
  apt: name=git state=latest update_cache=yes

- name: Install gitg
  become: yes
  apt: name=gitg

- name: Install Helix Visual Client (P4V)
  unarchive:
    src: http://cdist2.perforce.com/perforce/r17.2/bin.linux26x86_64/p4v.tgz
    dest: $HOME/opt/
    remote_src: yes
