---
- name: Add git PPA
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
    codename: '{{ distrib_codename }}'

- name: Install git
  become: yes
  apt: name=git state=latest update_cache=yes
