---
- name: Install java
  become: yes
  apt: name=openjdk-8-jdk

- name: Install JDK sources
  become: yes
  apt: name=openjdk-8-source

- stat: path="{{ home_dir }}/opt/idea/bin/idea.sh"
  register: idea_sh_file

- stat: path="/tmp/idea.tar.gz"
  register: idea_tar_file

# Work around https://github.com/ansible/ansible/issues/23864
- name: Download IntelliJ IDEA
  get_url:
    url: https://download-cf.jetbrains.com/idea/ideaIU-2018.3.tar.gz
    dest: /tmp/idea.tar.gz
    checksum: sha256:bca38957db9191d8932d79feca899ce4bb4cc8d32d4534de054a6541ac89ab5d
    timeout: 300
  when: idea_sh_file.stat.exists == False and idea_tar_file.stat.exists == False

- name: Creates idea directory
  file: path="{{ home_dir }}/opt/idea" state=directory

- name: Install IntelliJ IDEA
  unarchive:
    src: /tmp/idea.tar.gz
    dest: "{{ home_dir }}/opt/idea"
    extra_opts: [--strip-components=1]
    creates: "{{ home_dir }}/opt/idea/bin/idea.sh"

# Configuration for inotify watches limit
# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Copy sysctl configuration file
  copy:
    src: 90-intellij-idea.conf
    dest: /etc/sysctl.d/90-intellij-idea.conf
  become: yes
