---
- name: Install java
  become: yes
  apt: name=default-jdk

- name: Install JDK sources
  become: yes
  apt: name=openjdk-8-source

- stat: path="{{ home_dir }}/opt/idea-IU-173.3727.127/bin/idea.sh"
  register: idea_sh_file

# Work around https://github.com/ansible/ansible/issues/23864
- name: Download IntelliJ IDEA
  get_url:
    url: https://download-cf.jetbrains.com/idea/ideaIU-2017.3-no-jdk.tar.gz
    dest: /tmp/ideaIU-2017.3-no-jdk.tar.gz
    checksum: sha256:9a1f7d10b20ac578ba6f20c76b4dd9689260f33eeda888c556d1bdbf4d843171
    timeout: 300
  when: idea_sh_file.stat.exists == False

- name: Install IntelliJ IDEA
  unarchive:
    src: /tmp/ideaIU-2017.3-no-jdk.tar.gz
    dest: "{{ home_dir }}/opt/"
    creates: "{{ home_dir }}/opt/idea-IU-173.3727.127/bin/idea.sh"

# Configuration for inotify watches limit
# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Copy sysctl configuration file
  copy:
    src: 90-intellij-idea.conf
    dest: /etc/sysctl.d/90-intellij-idea.conf
  become: yes
