---
- name: "Install pyenv"
  shell: curl -L https://github.com/fernandoacorreia/pyenv-installer/raw/master/bin/pyenv-installer | bash
  args:
    creates: "{{ home_dir }}/.pyenv"
    warn: False

- name: "Install Python 3.6.x"
  shell: "{{ home_dir }}/.pyenv/bin/pyenv install 3.6.6"
  args:
    creates: "{{ home_dir }}/.pyenv/versions/3.6.6/bin/python"
