---
- name: Get the username running Ansible
  local_action: command whoami
  register: username_on_the_host

- name: Set home directory
  set_fact:
    home_dir: "{{ lookup('env','HOME') }}"

- name: Create basic directories
  file: path={{ home_dir }}/{{ item }} state=directory
  with_items:
    - .config
    - opt
    - projects
    - scratch
    - secrets

- name: Update cache if it's out of date
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  become: yes
  apt: name={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - colordiff
    - curl
    - fonts-hack-ttf
    - htop
    - jq
    - keepass2
    - language-pack-en-base
    - less
    - pcregrep
    - scala
    - silversearcher-ag
    - software-properties-common
    - tree
    - xclip

- name: Install basic pip packages
  become: yes
  pip: name={{item}}
  with_items:
    - yolk3k

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes
