---
- name: Get the username running Ansible
  local_action: command whoami
  register: username_on_the_host

- name: Set home directory
  set_fact:
    home_dir: "{{ lookup('env','HOME') }}"

- name: Create basic directories
  file: path={{ home_dir }}/{{ item }} state=directory
  with_items:
    - .config
    - opt
    - opt/bin
    - projects
    - scratch
    - secrets

- name: Update cache if it's out of date
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  become: yes
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - build-essential
    - ca-certificates
    - colordiff
    - curl
    - dconf-cli
    - fonts-hack-ttf
    - htop
    - jq
    - keepassxc
    - language-pack-en-base
    - less
    - libbz2-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - pavucontrol
    - pcregrep
    - scala
    - silversearcher-ag
    - software-properties-common
    - tk-dev
    - tree
    - xclip
    - zlib1g-dev

- name: Install basic pip packages
  become: yes
  pip: name={{item}}
  with_items:
    - awscli
    - yolk3k

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes
