#!/bin/bash
#
# Install sbt.
# Source: http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html
#
# Must be run as root / sudo.
#
set -o nounset -o errexit -o pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function die() { echo >&2 "$@"; exit 1; }

echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
apt-get update
apt-get install sbt
