---
- name: Set homefiles directory
  set_fact:
    homefiles_dir: "{{ lookup('env','HOME') }}/homefiles"

- name: Pull homefiles submodules
  shell: cd $HOME/homefiles && git submodule init && git submodule update
  args:
    creates: $HOME/homefiles/vendor/antigen/antigen.zsh

- name: Create secrets directory
  file: path=$HOME/secrets state=directory

- name: Create secrets README
  shell: echo "# Shell files exporting secrets as environment variables." > $HOME/secrets/README
  args:
    creates: $HOME/secrets/README

- name: Get status for ~/bin
  stat:
    path: "{{ home_dir }}/bin"
  register: home_bin

- name: Preserve existing ~/bin
  command: mv "{{ home_dir }}/bin" "{{ home_dir }}/bin.bak"
  when: home_bin.stat.isdir is defined and home_bin.stat.isdir

- name: Create link for ~/bin
  file:
    src: "{{ homefiles_dir }}/bin"
    dest: "{{ home_dir }}/bin"
    state: link

- name: Get status for ~/.profile
  stat:
    path: "{{ home_dir }}/.profile"
  register: home_dot_profile

- name: Preserve existing ~/.profile
  command: mv "{{ home_dir }}/.profile" "{{ home_dir }}/.profile.bak"
  when: home_dot_profile.stat.isreg is defined and home_dot_profile.stat.isreg

- name: Create link for ~/.profile
  file:
    src: "{{ homefiles_dir }}/profile.sh"
    dest: "{{ home_dir }}/.profile"
    state: link

- name: Get status for ~/.bash_profile
  stat:
    path: "{{ home_dir }}/.bash_profile"
  register: home_dot_bash_profile

- name: Preserve existing ~/.bash_profile
  command: mv "{{ home_dir }}/.bash_profile" "{{ home_dir }}/.bash_profile.bak"
  when: home_dot_bash_profile.stat.isreg is defined and home_dot_bash_profile.stat.isreg

- name: Create link for ~/.bash_profile
  file:
    src: "{{ homefiles_dir }}/bash_profile.sh"
    dest: "{{ home_dir }}/.bash_profile"
    state: link

- name: Get status for ~/.bashrc
  stat:
    path: "{{ home_dir }}/.bashrc"
  register: home_dot_bashrc

- name: Preserve existing ~/.bashrc
  command: mv "{{ home_dir }}/.bashrc" "{{ home_dir }}/.bashrc.bak"
  when: home_dot_bashrc.stat.isreg is defined and home_dot_bashrc.stat.isreg

- name: Create link for ~/.bashrc
  file:
    src: "{{ homefiles_dir }}/bashrc.sh"
    dest: "{{ home_dir }}/.bashrc"
    state: link

- name: Get status for ~/.zshrc
  stat:
    path: "{{ home_dir }}/.zshrc"
  register: home_dot_zshrc

- name: Preserve existing ~/.zshrc
  command: mv "{{ home_dir }}/.zshrc" "{{ home_dir }}/.zshrc.bak"
  when: home_dot_zshrc.stat.isreg is defined and home_dot_zshrc.stat.isreg

- name: Create link for ~/.zshrc
  file:
    src: "{{ homefiles_dir }}/zshrc.sh"
    dest: "{{ home_dir }}/.zshrc"
    state: link
