#!/bin/bash
#
# Installs Docker CE.
#
set -o nounset -o errexit -o pipefail

# The name of the user to be added to the docker group must be passed as an argument.
USER_TO_ADD=$1

# Load OS release file for Linux Mint support.
if [ -f "/etc/os-release" ]; then
  source "/etc/os-release"
fi

# Set release
release=${UBUNTU_CODENAME:-$(lsb_release -cs)}

# Add Docker’s official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Set up Docker's stable repository
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${release} stable"

# Install package
apt-get update
apt-get install -y docker-ce

# Add user to docker group
usermod -aG docker ${USER_TO_ADD}

# Configure Docker to start on boot
systemctl enable docker
