---
- name: Add git PPA
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
    codename: '{{ distrib_codename }}'

- name: Install git
  become: yes
  apt: name=git state=latest update_cache=yes

- name: Install gitg
  become: yes
  apt: name=gitg

- name: Create p4v directory
  file: path="{{ home_dir }}/opt/p4v" state=directory

- name: Install Helix Visual Client (P4V)
  unarchive:
    src: http://www.perforce.com/downloads/perforce/r18.2/bin.linux26x86_64/p4v.tgz
    dest: "{{ home_dir }}/opt/p4v"
    extra_opts: [--strip-components=1]
    creates: "{{ home_dir }}/opt/p4v/bin/p4v"
    remote_src: yes
