---
- hosts: all

  vars:
    distrib_codename: "{{ lookup('env', 'DISTRIB_CODENAME') }}"
    node_version: "8.11.3"

  roles:
  - common
  - git
  - tig
  - docker
  - docker-compose
  - java
  - sbt
  - zsh
  - lnav
  - homefiles
  - ripgrep
  - fzf
  - neovim
  - chrome
  - zoom
  - node
  - pyenv
  - keybase
  - virtualbox
  - wrk2
