---
- hosts: all

  vars:
    distrib_codename: "{{ lookup('env', 'DISTRIB_CODENAME') }}"

  roles:
  - common
  - git
  - tig
  - docker
  - java
  - sbt
  - zsh
  - lnav
  - homefiles
  - ripgrep
  - fzf
  - neovim
  - chrome
  - zoom
