---
- name: Set homefiles directory
  set_fact:
    homefiles_dir: "{{ lookup('env','HOME') }}/homefiles"

- name: Pull homefiles submodules
  shell: cd $HOME/homefiles && git submodule init && git submodule update

- name: Create secrets README
  shell: echo "# Shell files exporting secrets as environment variables." > $HOME/secrets/README
  args:
    creates: "{{ home_dir }}/secrets/README"

- name: Get status for ~/bin
  stat:
    path: "{{ home_dir }}/bin"
  register: home_bin

- name: Preserve existing ~/bin
  command: mv "{{ home_dir }}/bin" "{{ home_dir }}/bin.bak"
  when: home_bin.stat.isdir is defined and home_bin.stat.isdir

- name: Create link for ~/bin
  file:
    src: "{{ homefiles_dir }}/bin"
    dest: "{{ home_dir }}/bin"
    state: link

- name: Get status for ~/.profile
  stat:
    path: "{{ home_dir }}/.profile"
  register: home_dot_profile

- name: Preserve existing ~/.profile
  command: mv "{{ home_dir }}/.profile" "{{ home_dir }}/.profile.bak"
  when: home_dot_profile.stat.isreg is defined and home_dot_profile.stat.isreg

- name: Create link for ~/.profile
  file:
    src: "{{ homefiles_dir }}/shell/profile.sh"
    dest: "{{ home_dir }}/.profile"
    state: link

- name: Get status for ~/.bash_profile
  stat:
    path: "{{ home_dir }}/.bash_profile"
  register: home_dot_bash_profile

- name: Preserve existing ~/.bash_profile
  command: mv "{{ home_dir }}/.bash_profile" "{{ home_dir }}/.bash_profile.bak"
  when: home_dot_bash_profile.stat.isreg is defined and home_dot_bash_profile.stat.isreg

- name: Create link for ~/.bash_profile
  file:
    src: "{{ homefiles_dir }}/shell/bash_profile.sh"
    dest: "{{ home_dir }}/.bash_profile"
    state: link

- name: Get status for ~/.bashrc
  stat:
    path: "{{ home_dir }}/.bashrc"
  register: home_dot_bashrc

- name: Preserve existing ~/.bashrc
  command: mv "{{ home_dir }}/.bashrc" "{{ home_dir }}/.bashrc.bak"
  when: home_dot_bashrc.stat.isreg is defined and home_dot_bashrc.stat.isreg

- name: Create link for ~/.bashrc
  file:
    src: "{{ homefiles_dir }}/shell/bashrc.sh"
    dest: "{{ home_dir }}/.bashrc"
    state: link

- name: Get status for ~/.zshrc
  stat:
    path: "{{ home_dir }}/.zshrc"
  register: home_dot_zshrc

- name: Preserve existing ~/.zshrc
  command: mv "{{ home_dir }}/.zshrc" "{{ home_dir }}/.zshrc.bak"
  when: home_dot_zshrc.stat.isreg is defined and home_dot_zshrc.stat.isreg

- name: Create link for ~/.zshrc
  file:
    src: "{{ homefiles_dir }}/shell/zshrc.sh"
    dest: "{{ home_dir }}/.zshrc"
    state: link

- name: Get status for ~/.editorconfig
  stat:
    path: "{{ home_dir }}/.editorconfig"
  register: home_dot_editorconfig

- name: Preserve existing ~/.editorconfig
  command: mv "{{ home_dir }}/.editorconfig" "{{ home_dir }}/.editorconfig.bak"
  when: home_dot_editorconfig.stat.isreg is defined and home_dot_editorconfig.stat.isreg

- name: Create link for ~/.editorconfig
  file:
    src: "{{ homefiles_dir }}/.editorconfig"
    dest: "{{ home_dir }}/.editorconfig"
    state: link

- name: Get status for ~/.gitconfig
  stat:
    path: "{{ home_dir }}/.gitconfig"
  register: home_dot_gitconfig

- name: Preserve existing ~/.gitconfig
  command: mv "{{ home_dir }}/.gitconfig" "{{ home_dir }}/.gitconfig.bak"
  when: home_dot_gitconfig.stat.isreg is defined and home_dot_gitconfig.stat.isreg

- name: Create link for ~/.gitconfig
  file:
    src: "{{ homefiles_dir }}/git/gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    state: link

- name: Get status for ~/.fzf
  stat:
    path: "{{ home_dir }}/.fzf"
  register: home_dot_fzf

- name: Preserve existing ~/.fzf
  command: mv "{{ home_dir }}/.fzf" "{{ home_dir }}/.fzf.bak"
  when: home_dot_fzf.stat.isdir is defined and home_dot_fzf.stat.isdir

- name: Create link for ~/.fzf
  file:
    src: "{{ homefiles_dir }}/vendor/fzf"
    dest: "{{ home_dir }}/.fzf"
    state: link

- name: Get status for ~/.Xmodmap
  stat:
    path: "{{ home_dir }}/.Xmodmap"
  register: home_dot_Xmodmap

- name: Preserve existing ~/.Xmodmap
  command: mv "{{ home_dir }}/.Xmodmap" "{{ home_dir }}/.Xmodmap.bak"
  when: home_dot_Xmodmap.stat.isreg is defined and home_dot_Xmodmap.stat.isreg

- name: Create link for ~/.Xmodmap
  file:
    src: "{{ homefiles_dir }}/X/Xmodmap"
    dest: "{{ home_dir }}/.Xmodmap"
    state: link
